apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: scheduling-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app

  template:
    metadata:
      labels:
        app: backend-app

    spec:
      # tolerations:
      # - key: "training"
      #   operator: "Equal"
      #   value: "devops"
      #   effect: "NoSchedule"

      # affinity:
      #   podAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 100
      #       podAffinityTerm:
      #         labelSelector:
      #           matchExpressions:
      #           - key: app
      #             operator: In
      #             values:
      #             - college-portal
      #         topologyKey: "kubernetes.io/hostname"

      containers:
      - name: backend-container
        image: nginx
        ports:
        - containerPort: 80