apiVersion: apps/v1
kind: Deployment
metadata:
  name: college-portal
  namespace: scheduling-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: college-portal
  template:
    metadata:
      labels:
        app: college-portal
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: training
                operator: In
                values:
                - devops

        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - college-portal
              topologyKey: "kubernetes.io/hostname"

      containers:
      - name: college-portal-container
        image: kajapathyk/duniversity-college-portal:latest
        ports:
        - containerPort: 3000